mk-inst-story:
    mkdir -p output
    rm -f ./output/*
    # for img in *.jpg; do magick "$img" -resize 1300x2500 -gravity center -background '#0c1016' -extent 1440x2560 "output/$img"; done
    for img in *.jpg; do magick "$img" -resize 1330x2500 -gravity center -background 'black' -extent 1440x2560 "output/$img"; done
    rm -f $HOME/cloud/share/*
    cp ./output/* $HOME/cloud/share/

mk-pdf:
    mkdir -p output
    rm -f ./output/*
    mogrify -path output -background black -bordercolor black -border 50x50 -resize 1600x2400^ -gravity center -extent 1600x2400 *.jpg
    convert output/*.jpg -background black images.pdf

mk-inst-post:
    mkdir -p output
    rm -f ./output/*
    for img in *.jpg; do magick "$img" -resize 2500x2500 -gravity center -background white -extent 2600x2600 "output/$img"; done

clean:
    rm -f ./output/*
    rm -f ./*.jpg

sync:
    rsync -av --delete ./all-starts/* grig@192.168.1.118:/mnt/passport/photos 
