#!/bin/sh

xrandr --output HDMI-2 --mode 1920x1080 --rate 60
xrandr --output DP-0 --mode 2560x1440 --rate 144
setxkbmap us,ru pc105 grp:alts_toggle

xcompmgr & 
unclutter &
xwallpaper --zoom "$HOME/.local/share/bg/fern.jpg" &

exec dwm
