#!/usr/bin/env sh

runsvdir $HOME/.local/service > /dev/null 2> /dev/null &
xrandr --output DP-0 --mode 2560x1440 --rate 144 

if [ -f $HOME/.local/state/wallpaper.jpg ]; then
    feh --bg-fill $HOME/.local/state/wallpaper.jpg
fi

$HOME/.config/mind-shift/launch.sh
exec dbus-run-session /usr/bin/qtile start 
