mk-inst-story:
    mkdir -p output
    rm -f ./output/*
    # for img in *.jpg; do magick "$img" -resize 1300x2500 -gravity center -background '#0c1016' -extent 1440x2560 "output/$img"; done
    for img in *.jpg; do magick "$img" -resize 1300x2500 -gravity center -background 'white' -extent 1440x2560 "output/$img"; done
    # rm -f $HOME/cloud/share/*
    cp ./output/* $HOME/cloud/share/*

mk-pdf:
    mkdir -p output
    rm -f ./output/*
    mogrify -path output -bordercolor White -border 100x100 -resize 2560x1440 -gravity center -extent 2560x1440 *.jpg
    convert output/*.jpg images.pdf

mk-inst-post:
    mkdir -p output
    rm -f ./output/*
    for img in *.jpg; do magick "$img" -resize 2500x2500 -gravity center -background white -extent 2600x2600 "output/$img"; done

clean:
    rm -f ./output/*
    rm -f ./*.jpg

