#!/usr/bin/env dash

ROOT_WIN=466
SCREEN_WIDTH=2560

eval $(xdotool getmouselocation --shell)

if [ "$WINDOW" = "$ROOT_WIN" ]; then
    if [ "$X" -lt $(($SCREEN_WIDTH / 2)) ]; then
        qtile cmd-obj -o screen -f next_group
    fi
fi
