theme = "grig"


[editor]
line-number = "relative"
cursorline = true
color-modes = true
insert-final-newline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
character = "┊"
render = true
skip-levels = 1

[editor.statusline]
left = [
  "mode",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["diagnostics"]
right = ["workspace-diagnostics", "register", "spinner"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"


[keys.insert]
esc = ["normal_mode", ":run-shell-command on-insert-exit"]

[keys.normal]
a = ["insert_mode", ":run-shell-command on-insert-enter"]
A = ["insert_at_line_start", ":run-shell-command on-insert-enter"]
t = ["append_mode", ":run-shell-command on-insert-enter"]
T = ["insert_at_line_end", ":run-shell-command on-insert-enter"]
w = ["open_below", ":run-shell-command on-insert-enter"]
W = ["open_above", ":run-shell-command on-insert-enter"]

o = "move_next_word_start"
O = "move_next_long_word_start"
n = "move_prev_word_start"
N = "move_prev_long_word_start"

pageup = "page_cursor_half_up"
pagedown = "page_cursor_half_down"

r = "replace_with_yanked"
h = "hover"
j = "join_selections"
l = "find_till_char"
L = "till_prev_char"
tab = "goto_last_accessed_file"
home = "goto_first_nonwhitespace"

C-s = ":wa"
C-q = ":wqa"
C-a = "code_action"
C-f = "file_picker"
C-pageup = "goto_file_start"
C-pagedown = "goto_file_end"

F5 = ":config-reload"

[keys.normal.e]
e = "move_prev_word_end"
m = "search_prev"
d = "goto_prev_diag"
n = "search_prev"

[keys.normal.i]
e = "move_next_word_end"
m = "search_next"
d = "goto_prev_diag"
n = "search_next"

[keys.normal.g]
u = "goto_reference"
t = "goto_type_definition"

[keys.select]
o = "extend_next_word_start"
O = "extend_next_long_word_start"
n = "extend_prev_word_start"
N = "extend_prev_long_word_start"
