public-key := "age18hjjgcy2jzhwj7qjrp8t8pdrmhckygdt4mv45nqqtcfx9cd8ng3snfls4y"

encrypt file:
    age --encrypt -r {{public-key}} -o {{file}}.age {{file}}

decrypt private-key-file file :
    age --decrypt -i {{private-key-file}} -o {{trim_end_match(file, ".age")}} {{file}}
    chmod --reference={{file}} {{trim_end_match(file, ".age")}} 
