stow: remove-broken-links
    stow --dotfiles --no-folding -t $HOME -d "{{justfile_directory()}}" -S home

stow-secrets private-key-file: remove-broken-links
    just -f ./home-secrets/justfile decrypt-all {{private-key-file}}
    stow --dotfiles --no-folding -t $HOME -d "{{justfile_directory()}}" -S home-secrets

stow-root:
    sudo stow --dotfiles --no-folding -t / -d "{{justfile_directory()}}" -S root

[working-directory: "/home/grig/"]
remove-broken-links:
    cd $HOME
    find . -xtype l -delete
