---
- name: Setup xkb
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Copy layout to /usr/share/X11/xkb/symbols/ru
      become: yes
      blockinfile:
        dest: /usr/share/X11/xkb/symbols/ru
        content: "{{ lookup('file', './xkb/ru-grig.xkb') }}"
        marker: "// {mark} ANSIBLE MANAGED BLOCK"    
        prepend_newline: true

    - name: Add variant to /usr/share/X11/xkb/rules/evdev.xml
      become: yes
      blockinfile:
        dest: /usr/share/X11/xkb/rules/evdev.xml
        insertafter: '<description>Russian \(phonetic\)</description>'
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"    
        content: |
          </configItem>
          </variant>
          <variant>
          <configItem>
          <name>grig</name>
          <description>Russian (grig)</description>

    - name: Update xkb cache
      become: yes
      command: dpkg-reconfigure xkb-data

    - name: Install psutil
      become: yes
      apt:
        name: python3-psutil

    # some kind of bug with this options, can't put it in a list
    - name: Set dconf options
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'ru+grig')]"

    - name: Set dconf options
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/gnome/desktop/input-sources/per-window", value: "true" }
        - { key: "/org/gnome/desktop/input-sources/xkb-options", value: "['lv3:ralt_switch']" }
