---
- name: Gnome setup
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Remove packages
      apt:
        name: gnome-tour
        state: absent

    - name: Install packages
      apt:
        pkg:
          - python3-psutil
          - bibata-cursor-theme
          - gnome-shell-extensions
          - gnome-shell-extension-prefs

    - name: Set cursor
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/gnome/desktop/interface/cursor-theme", value: "'Bibata-Modern-Ice'" }
        - { key: "/org/gnome/desktop/interface/cursor-size", value: "22" }

    - name: Setup keybindings
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/gnome/settings-daemon/plugins/media-keys/screenreader", value: "''" }

        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Cycle audio sources'" }
        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'/home/grig/.local/bin/audio-sink-cycle'" }
        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Alt><Super>S'" }

        - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings", value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']" }
