---
- name: Gnome setup
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Remove packages
      apt:
        name: gnome-tour
        state: absent

    - name: Install packages
      apt:
        pkg:
          - python3-psutil
          - bibata-cursor-theme
          - gnome-shell-extensions
          - gnome-shell-extension-prefs

    - name: Set cursor
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "/org/gnome/desktop/interface/cursor-theme", value: "'Bibata-Modern-Ice'" }
        - { key: "/org/gnome/desktop/interface/cursor-size", value: "22" }
