---
- name: Setup Gnome
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Remove packages
      apt:
        pkg:
          - gnome-tour
        state: absent

    - name: Install packages
      apt:
        pkg:
          - python3-psutil
          - gnome-shell-extensions
          - gnome-shell-extension-prefs
        state: present

    # - name: Set dconf options
    #   community.general.dconf:
    #     key: "{{ item.key }}"
    #     value: "{{ item.value }}"
    #   loop:
    #     - { key: "/org/gnome/desktop/input-sources/per-window", value: "true" }
    #     - { key: "/org/gnome/desktop/input-sources/xkb-options", value: "['lv3:ralt_switch']" }
