---
- name: Npm packages setup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install node packages
      community.general.npm:
        name: "{{ item }}"
        global: true
      loop:
        - bun
        - typescript
        - typescript-language-server
