---
- name: Homebrew packages setup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      loop:
        - stow
        - just
        - lazygit
        - sk
        - helix
        - yazi
        - imagemagick
        - fd
        - bottom
        - yt-dlp
        - tree
        - tldr
        - nushell

        - marksman # makrdown lsp
        - taplo # toml lsp
        - yaml-language-server # yaml lsp
        
        - go
        - gopls

        - rust

        - node
