---
- name: Packages setup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install apt packages
      become: yes
      apt:
        update_cache: yes
        pkg:
          - build-essential
          - fish
          - curl
          - wget
          - unzip
          - zip
          - git
          - tmux
          - direnv
          - flatpak
          - age
          - bc
          - proxychains4

          - zathura
          - gnome-boxes

          - libxcb-xinerama0
          - libxcb-cursor0
          - libdbus-glib-1-2


    - name: Add Flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Grant filesystem permissions to all Flatpak applications (user)
      command: "flatpak override --user --filesystem=home"

    - name: Install flatpack applications
      community.general.flatpak:
        name: "{{ item }}"
      loop:
        - app.zen_browser.zen
        - org.telegram.desktop
        - org.qbittorrent.qBittorrent
        - org.darktable.Darktable
        - md.obsidian.Obsidian
        - org.remmina.Remmina
        - fm.reaper.Reaper
        - com.discordapp.Discord
        - org.chromium.Chromium
        - org.libreoffice.LibreOffice
        - uk.org.greenend.chiark.sgtatham.putty
        - net.ankiweb.Anki
        - org.videolan.VLC
        - io.mpv.Mpv
        - com.github.johnfactotum.Foliate
        - org.localsend.localsend_app
        - org.gimp.GIMP


    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      loop:
        - stow
        - just
        - lazygit
        - sk
        - helix
        - yazi
        - imagemagick
        - fd
        - bottom
        - yt-dlp
        - tree
        - tldr

        - marksman # makrdown lsp
        - taplo # toml lsp
        - yaml-language-server # yaml lsp
        
        - go
        - gopls

        - rust

        - node

    - name: Install node packages
      community.general.npm:
        name: "{{ item }}"
        global: true
      loop:
        - bun
        - typescript
        - typescript-language-server
