---
- name: Create cron job for rsync
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Ensure rsync is installed
      apt:
        name: rsync
        state: present
        update_cache: yes

    - name: Create cron job 
      cron:
        name: "Sync ideavim config"
        hour: "*"
        job: rsync --delete /mnt/c/Users/grig/.config/ideavim /home/grig/cloud/resources/configs/
