---
- name: Setup Syncthing
  hosts: localhost
  vars_files:
    - secrets.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install Syncthing
      apt:
        name: syncthing
        state: present
      become: yes

    - name: Create Syncthing config directory
      file:
        path: ~/.local/share/syncthing
        state: directory
        mode: '0700'

    - name: Create Syncthing certificate file
      copy:
        content: "{{ vars[ansible_hostname + '_syncthing_cert'] }}"
        dest: ~/.local/share/syncthing/cert.pem
        mode: '0644'
      when: (ansible_hostname + '_syncthing_cert') in vars

    - name: Create Syncthing private key file
      copy:
        content: "{{ vars[ansible_hostname + '_syncthing_key'] }}"
        dest: ~/.local/share/syncthing/key.pem
        mode: '0600'
      when: (ansible_hostname + '_syncthing_key') in vars

    - name: Create user systemd directory
      file:
        path: ~/.config/systemd/user
        state: directory
        mode: '0755'

    - name: Create Syncthing user systemd service file
      copy:
        content: |
          [Unit]
          Description=Syncthing - Open Source Continuous File Synchronization
          Documentation=man:syncthing(1)
          After=network.target

          [Service]
          ExecStart=/usr/bin/syncthing serve --no-browser --no-restart --logflags=0
          Restart=on-failure
          RestartSec=5
          SuccessExitStatus=3 4
          RestartForceExitStatus=3 4

          # Hardening
          SystemCallArchitectures=native
          MemoryDenyWriteExecute=true
          NoNewPrivileges=true

          [Install]
          WantedBy=default.target
        dest: ~/.config/systemd/user/syncthing.service
        mode: '0644'

    - name: Reload user systemd daemon
      systemd:
        daemon_reload: yes
        scope: user

    - name: Enable and start Syncthing user service
      systemd:
        name: syncthing
        enabled: yes
        state: started
        scope: user

    - name: Open web gui
      shell: xdg-open http://127.0.0.1:8384/
