---
- import_playbook: pkgs_wsl.yml
- import_playbook: ssh.yml
- import_playbook: neovim.yml
- import_playbook: repos.yml
- import_playbook: shadowsocks.yml
- import_playbook: syncthing.yml
- import_playbook: docker.yml
