---
- name: Setup ssh 
  hosts: localhost
  vars_files:
    - secrets.yml
  tasks:

    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Copy SSH private key
      copy:
        content: "{{ ssh_private_key }}"
        dest: ~/.ssh/id_ed25519
        mode: '0600'

    - name: Add known_hosts
      known_hosts:
        name: 'github.com'
        key: 'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl' 
