---
- name: Setup Shadowsocks 
  hosts: localhost
  vars_files:
    - secrets.yml
  tasks: 

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install shadowsocks-libev
      apt:
        name: shadowsocks-libev
        state: present
      become: yes

    - name: Ensure .config/shadowsocks directory exists
      file:
        path: ~/.config/shadowsocks
        state: directory
        mode: '0700'

    - name: Copy shadowsocks-fi config
      copy:
        content: "{{ shadowsocks_fi }}"
        dest: ~/.config/shadowsocks/config-fi.json
        mode: '0644'

    - name: Copy shadowsocks-nl config
      copy:
        content: "{{ shadowsocks_nl }}"
        dest: ~/.config/shadowsocks/config-nl.json
        mode: '0644'

    - name: Create user systemd directory
      file:
        path: ~/.config/systemd/user
        state: directory
        mode: '0755'

    - name: Create shadowsocks-fi user systemd service file
      copy:
        content: |
          [Unit]
          Description=Shadowsocks-fi Client
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/ss-local -c %h/.config/shadowsocks/config-fi.json
          Restart=always
          RestartSec=3
          KillMode=mixed

          [Install]
          WantedBy=default.target
        dest: ~/.config/systemd/user/shadowsocks-fi.service
        mode: '0644'

    - name: Create shadowsocks-nl user systemd service file
      copy:
        content: |
          [Unit]
          Description=Shadowsocks-nl Client
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/ss-local -c %h/.config/shadowsocks/config-nl.json
          Restart=always
          RestartSec=3
          KillMode=mixed

          [Install]
          WantedBy=default.target
        dest: ~/.config/systemd/user/shadowsocks-nl.service
        mode: '0644'

    - name: Reload user systemd daemon
      systemd:
        daemon_reload: yes
        scope: user

    - name: Enable and start shadowsocks user service
      systemd:
        name: shadowsocks-fi
        enabled: yes
        state: started
        scope: user

    - name: Enable and start shadowsocks-nl user service
      systemd:
        name: shadowsocks-nl
        enabled: yes
        state: started
        scope: user
