---
- name: Setup packages
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install apt packages
      become: yes
      apt:
        update_cache: yes
        pkg:
          - build-essential
          - fish
          - curl
          - wget
          - unzip
          - zip
          - git
          - tmux
          - tmuxp
          - tldr
          - direnv
          - flatpak
          - age
          - bc

          - zathura
          - gnome-boxes


    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      loop:
        - stow
        - just
        - lazygit
        - sk
        - helix
        - yazi
        - imagemagick
        - fd
        - bottom
        - yt-dlp
        - tree

        # lsp
        - marksman # makrdown
        - taplo # toml
        - yaml-language-server # yaml
     

    - name: Add Flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpack applications
      community.general.flatpak:
        name: "{{ item }}"
      loop:
        - app.zen_browser.zen
        - org.telegram.desktop
        - org.qbittorrent.qBittorrent
        - org.darktable.Darktable
        - md.obsidian.Obsidian
        - org.remmina.Remmina
        - fm.reaper.Reaper
        - com.discordapp.Discord
        - org.chromium.Chromium
        - org.libreoffice.LibreOffice
        - uk.org.greenend.chiark.sgtatham.putty
