---
- name: Shadowsocks setup 
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml

  tasks: 
    - name: Install shadowsocks-libev
      apt:
        pkg: 
          - shadowsocks-libev
          - proxychains4
      become: yes

    - name: Ensure .config/shadowsocks directory exists
      file:
        path: ~/.config/shadowsocks
        state: directory
        mode: '0700'

    - name: Create user systemd directory
      file:
        path: ~/.config/systemd/user
        state: directory
        mode: '0755'

    - name: Creating config
      copy:
        content: "{{ item.config }}"
        dest: ~/.config/shadowsocks/config-{{ item.name }}.json
        mode: '0644'
      loop:
        - { name: "fi", config: "{{ shadowsocks_fi }}" }
        - { name: "nl", config: "{{ shadowsocks_nl }}" }

    - name: Create user systemd service file
      copy:
        content: |
          [Unit]
          Description=Shadowsocks-{{ item }} Client
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/ss-local -c %h/.config/shadowsocks/config-{{ item }}.json
          Restart=always
          RestartSec=3
          KillMode=mixed

          [Install]
          WantedBy=default.target
        dest: ~/.config/systemd/user/shadowsocks-{{ item }}.service
        mode: '0644'
      loop:
        - fi
        - nl

    - name: Reload user systemd daemon
      systemd:
        daemon_reload: yes
        scope: user

    - name: Enable and start shadowsocks user service
      systemd:
        name: shadowsocks-{{ item }}
        enabled: yes
        state: restarted
        scope: user
      loop:
        - fi
        - nl

    - name: Create proxychains config
      become: yes
      copy:
        dest: /etc/proxychains4.conf
        content: |
          strict_chain
          quiet_mode
          tcp_read_time_out 5000
          tcp_connect_time_out 3000

          [ProxyList]
          socks5 127.0.0.1 1080
