---
- name: Syncthing setup
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml

  tasks:
    - name: Install synctihng
      apt:
        update_cache: yes
        name: syncthing
        state: present
      become: yes

    - name: Create user systemd directory
      file:
        path: ~/.config/systemd/user
        state: directory
        mode: '0755'

    - name: Create Syncthing user systemd service file
      copy:
        content: |
          [Unit]
          Description=Syncthing - Open Source Continuous File Synchronization
          Documentation=man:syncthing(1)
          After=network.target

          [Service]
          ExecStart=/usr/bin/syncthing serve --no-browser --no-restart --logflags=0
          Restart=on-failure
          RestartSec=5
          SuccessExitStatus=3 4
          RestartForceExitStatus=3 4

          # Hardening
          SystemCallArchitectures=native
          MemoryDenyWriteExecute=true
          NoNewPrivileges=true

          [Install]
          WantedBy=default.target
        dest: ~/.config/systemd/user/syncthing.service
        mode: '0644'

    - name: Reload user systemd daemon
      systemd:
        daemon_reload: yes
        scope: user

    - name: Enable and start Syncthing user service
      systemd:
        name: syncthing
        enabled: yes
        state: started
        scope: user

    - name: Open web gui
      shell: xdg-open http://127.0.0.1:8384/
